name : Snort To Slack
on :
  workflow_run :
    workflows : [Snort Automation]
    types : 
      - completed
      
jobs : 
  build :
    runs-on : self-hosted
    steps :

    - name : execute
      run : python snort_result_to_slack.py
