name : Snort Automation
on :
  push :
   branches : 
      - master
   paths :
      - "rule_test/**"
      
jobs : 
  build :
    runs-on : self-hosted
    steps :

    - name : test
      run : python "https://github.com/1x2nov/axgate-cert/blob/master/snort%20automation.py"
