name : Snort Automation
on :
  workflow_run :
    workflows : [Checkout]
    types : 
      - completed
      
jobs : 
  build :
    runs-on : self-hosted
    steps :

    - name : execute
      run : python snort_automation.py
