name : Github Actions Test
on :
  push :
    branches : master

jobs : 
  build :
    runs-on : ubuntu-latest
    steps :
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: teichae/node
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      
      - name: Docker Buildxt Test
        uses: docker/setup-buildx-action@v1

      - name: Docker Login Test
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
