name : Github Actions Test
on :
  push :
    branches : master


jobs :
  build :
    runs-on : ubuntu-latest
    steps :
      - name: Docker Buildxt Test
        uses: docker/setup-buildx-action@v1

      - name: Docker Login Test
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name : Docker Image Test
        uses : docker/build-push-action@v2
        with :
          context : /snort_docker
          file : /snort_docker/snort_docker
          platforms : linux/amd64
          push : true
