name : Github Actions docker Test
on :
  push :
    branches : master

jobs : 
  build :
    runs-on : ubuntu-latest
    steps :
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1

     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: docker hub image pull
       run : |
         docker login
         docker pull ${{ secrets.DOCKERHUB_USERNAME }}/snort-automation:1.0

     - name : Build TEST
       run : |
         docker run -i ${{ secrets.DOCKERHUB_USERNAME }}/snort-automation:1.0
         docker ps -a -q | grep ${{ secrets.DOCKERHUB_USERNAME }}/snort-automation:1.0 >> test.txt
         cat test.txt
