name : Github Actions docker Test
on :
  push :
    branches : master

jobs : 
  build :
    runs-on : ubuntu-latest
    steps :
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1

     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: docker hub image pull
       run : |
         docker login
         docker pull namhoonkooo/snort-automation:1.0

     - name : access test
       run : |
         docker run -i namhoonkooo/snort-automation:1.0 /bin/bash
         cd /snort
         ls -al
