name : Github Actions docker Test
on :
  push :
    branches : master

jobs : 
  build :
    runs-on : ubuntu-latest
    steps :
      - name: Docker Buildxt Test
        uses: docker/setup-buildx-action@v1

      - name: Docker Login Test
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Dockerhub image test
        id : docker_build
        uses : docker/build-push-actions@v2
        with :
          push : true
          tags : namhoonkooo/snort-automation:latest

      - name : Docker TEST
        run : |
          ls -al
 
