name : Github Actions docker Test
on :
  push :
    branches : master

jobs : 
  build :
    runs-on : ubuntu-22.04
    steps :
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


     - name : Build TEST
       uses : docker/build-push-action@v2
       with : 
         file : ./Dockerfile
         push : true
         tags : ${{ secrets.DOCKERHUB_USERNAME }}/snort-automation:latest
         cache-from : type=gha
         cache-to : type=gha,mode=max
